// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// conformal_predict
List conformal_predict(NumericVector train_x, NumericVector train_y, NumericVector test_x, double alpha);
RcppExport SEXP _SA24204186_conformal_predict(SEXP train_xSEXP, SEXP train_ySEXP, SEXP test_xSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type train_x(train_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type train_y(train_ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type test_x(test_xSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(conformal_predict(train_x, train_y, test_x, alpha));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SA24204186_conformal_predict", (DL_FUNC) &_SA24204186_conformal_predict, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_SA24204186(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
