# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Conformal Prediction for Regression
#' @name conformal_predict
#' @description 本函数基于简单的 conformal prediction 方法为每个测试数据点生成预测区间。
#' @param train_x 一个数值型向量，表示训练数据的特征（自变量）
#' @param train_y 一个数值型向量，表示训练数据的标签（目标值）
#' @param test_x 一个数值型向量，表示测试数据的特征（自变量）
#' @param alpha 一个介于 0 和 1 之间的数值，定义预测区间的置信水平
#' @return 一个包含每个测试数据点预测区间的列表，包含下界和上界。
#' @examples
#' train_x <- c(1, 2, 3, 4, 5)
#' train_y <- c(1.1, 2.0, 3.1, 4.2, 5.1)
#' test_x <- c(2.5, 3.5)
#' alpha <- 0.05
#' res <- conformal_predict(train_x, train_y, test_x, alpha)
#' print(res)
#' @export
conformal_predict <- function(train_x, train_y, test_x, alpha) {
    .Call('_SA24204186_conformal_predict', PACKAGE = 'SA24204186', train_x, train_y, test_x, alpha)
}

